//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobRequest
    {
        public int RequestId { get; set; }
        public Nullable<int> ServiceTypeId { get; set; }
        public Nullable<int> RequestUserId { get; set; }
        public string ImagePath { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public string Description { get; set; }
    
        public virtual Service Service { get; set; }
        public virtual User User { get; set; }
    }
}
